# Generated by Django 5.0.3 on 2025-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.CharField(choices=[('regular', 'Regular Bike'), ('electric', 'Electric Bike')], max_length=8)),
                ('frame', models.CharField(max_length=20)),
                ('wheels', models.CharField(max_length=20)),
                ('motor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bike_orders',
            field=models.ManyToManyField(blank=True, related_name='users', to='online_market.bikeorder'),
        ),
    ]
